name: 버그 리포트
description: 발견한 버그를 신고합니다
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        버그를 신고해 주셔서 감사합니다!
  - type: textarea
    id: bug-description
    attributes:
      label: 버그 설명
      description: 어떤 버그인지 명확하게 설명해주세요.
      placeholder: 버그가 발생했을 때...
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 재현 방법
      description: 버그를 재현하는 단계를 알려주세요.
      value: |
        1. '...' 화면으로 이동
        2. '....' 클릭
        3. '....' 입력
        4. 오류 발생
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 예상 동작
      description: 어떻게 동작해야 하는지 설명해주세요.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 스크린샷
      description: 가능하다면 스크린샷을 첨부해주세요.
  - type: dropdown
    id: browsers
    attributes:
      label: 브라우저
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - 기타
