name: 기능 요청
description: 새로운 기능이나 아이디어를 제안합니다
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        블로그메이트 프로젝트에 기여해 주셔서 감사합니다!
  - type: textarea
    id: feature-description
    attributes:
      label: 기능 설명
      description: 어떤 기능이 필요하신가요? 자세히 설명해주세요.
      placeholder: 이 기능은...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 구현 방법
      description: 이 기능을 어떻게 구현할 수 있을지 아이디어가 있으시면 공유해주세요.
  - type: textarea
    id: alternatives
    attributes:
      label: 대안
      description: 고려해본 다른 대안이 있나요?
  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      options:
        - 낮음
        - 중간
        - 높음
    validations:
      required: true
