spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
logging:
  level:
    com:
      blogmate: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
      springframework: INFO