spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    open-in-view: false

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogmate
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  config:
    activate:
      on-profile: local

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogmate
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  config:
    activate:
      on-profile: prd